### ISSUE TITLE
Fix 'path too long' issues with creating windows installer.

### ISSUE THREAD

**Issue by gbmhunter** [mbedded-ninja/NinjaTerm#10]
Packaging app working with 'npm run-script package', but 'grunt create-windows-installer' is having issues with path name length.

Options:
- Flatten node_modules dirs
- Archive node_modules dirs with ASAR (packaging app might already support this!)

**Comment by gamicklisafisher** [comment]
"Long Path Tool" is nice tool to handle this situation.

**Comment by gbmhunter** [comment]
I don't know if that would be applicable to an electron install?

I managed to fix it by creating an ASAR package, which is a good solution for other reasons also.
