### ISSUE TITLE
Add display support for horizontal tab characters.

### ISSUE THREAD

**Issue by Phlash7** [mbedded-ninja/NinjaTerm#211]
New to Arduino.  Evaluating terminal "only" programs for use in application roll out to others.
Noted that NiTe does not replicate Serial.print("/t") as screen tab as the IDE serial monitor does.
Suggestions / alternatives?

Regards:
Phlash7

**Comment by gbmhunter** [comment]
Hi Phlash7, hmm interesting, I would of hoped that NinjaTerm did display tabs correctly on screen! I will look into this in the next few days.

Aside from NinjaTerm, some other serial alternatives out there are PuTTy, minicom, RealTerm, Termite, Terminal by By@y, with my favourite being PuTTy.
