### ISSUE TITLE
Support Custom Baud Rates

### ISSUE THREAD

**Issue by fraza077** [mbedded-ninja/NinjaTerm#222]
Custom baud rates are useful, a lot of applications I'm working with don't use standard baud rates.

**Comment by gbmhunter** [comment]
Alrighty, I will have a look into the work needed to support this!

**Comment by gbmhunter** [comment]
Support added in v0.9.1 (https://github.com/mbedded-ninja/NinjaTerm/releases/tag/v0.9.1).
